### ISSUE TITLE
Test hangs

### ISSUE THREAD

**Issue by tov** [mmgeorge/rust-odata#1]
The output is:

```
running 1 test
test test::test::runme has been running for over 60 seconds
```

**Comment by mmgeorge** [comment]
Yes -- tests really are not there atm (basically just using that to drop in and make sure server is working, that's why it runs forever. Probably would be better to have a separate bin project for the ad hoc stuff... (too bad there's no repl)... Should have basic service-level stuff fixed up by tomorrow.

**Comment by mmgeorge** [comment]
Test fixed
